import { Snapshot } from '../../src/snapshots/snapshot.entity';

export const TEST_JPEG_BASE64 =
  '/9j/4AAQSkZJRgABAQEADwAPAAD/2wBDAEMuMjoyKkM6NjpLR0NPZKZsZFxcZMySmnmm8dT++u3U' +
  '6eX//////////+Xp////////////////////////////2wBDAUdLS2RXZMRsbMT//+n/////////' +
  '////////////////////////////////////////////////////////////wgARCAALAAsDASIA' +
  'AhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAECA//EABQBAQAAAAAAAAAAAAAAAAAAAAD/2gAM' +
  'AwEAAhADEAAAAa0Gf//EABYQAAMAAAAAAAAAAAAAAAAAAAEQMf/aAAgBAQABBQI1/wD/xAAUEQEA' +
  'AAAAAAAAAAAAAAAAAAAA/9oACAEDAQE/AX//xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oACAECAQE/' +
  'AX//xAAUEAEAAAAAAAAAAAAAAAAAAAAg/9oACAEBAAY/Ah//xAAZEAEAAgMAAAAAAAAAAAAAAAAB' +
  'ADEQEUH/2gAIAQEAAT8hT1ohUQWsf//aAAwDAQACAAMAAAAQ8//EABQRAQAAAAAAAAAAAAAAAAAA' +
  'AAD/2gAIAQMBAT8Qf//EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAIAQIBAT8Qf//EABkQAQACAwAA' +
  'AAAAAAAAAAAAAAEAERAxof/aAAgBAQABPxCx7IUI7qCFCmP/2Q==';

export function defaultSnapshot(): Snapshot {
  return new Snapshot(Buffer.from(TEST_JPEG_BASE64, 'base64'));
}
